### ISSUE TITLE
Handle multicast/broadcast communications

### ISSUE THREAD

**Issue by objectiser** [scribble/scribble-java#100]
Creating this issue as a placeholder for discussions about multicast and broadcast communications.

In scribble we can specify multiple 'to' roles which would enable different endpoints, representing different behaviours, to receive and use the same message.

However wondering whether we also need to cater for multiple (potentially unbounded) instances of a role(s) - I think we would need to find some real world examples to understand whether this is relevant.

If defining a global protocol, then would we have multiple recipients all behaving the same way - but doing something differently internally, to warrant it being considered equivalent from an externally observable behaviour perspective?

**Comment by rhu1** [comment]
Closing due to age.  Can reopen if needed in future.
