### ISSUE TITLE
Handling redirects, retries and fallbacks

### ISSUE THREAD

**Issue by objectiser** [scribble/scribble-java#102]
Microservices tend to use common infrastructure patterns to make the systems more resilient, for example circuit breakers to prevent services from being overloaded by returning a 'default' response, retry mechanisms, fallbacks, etc.

We need to examine how these are handled from a scribble protocol description and monitoring perspective.

**Comment by rhu1** [comment]
Closing due to age.  Can reopen if needed in future.
