### ISSUE TITLE
Monitor/Simulate mechanism for validating a stream of events/actions against FSM

### ISSUE THREAD

**Issue by objectiser** [scribble/scribble-java#104]
The initial requirement is to support simulation of a trace (series of sends/receives) against a set of FSMs - one per role (or service) being simulated.

However the more general case will be to manage a set of session instances, per role/service, over time - with the events being received in realtime. It is also possible that there will be multiple instances of the monitor (for load balancing/resilience purposes), so the session data needs to be persisted in a shared db/cache (should be pluggable to allow different implementations).

This means that the session needs a way to save the position within the FSM, for a particular session instance (and service/role), and then be able to recover it when a new event for an existing session instance is received.

So in the case of OpenTracing - the role will be determined by the service name, and the session instance by the trace id.

**Comment by rhu1** [comment]
To clarify: what is the "set of FSMs"?  Is it the set given by the roles of a session, or some subset of those?  Or perhaps an arbitrary set of roles across multiple sessions?

In any case, this should be easy to do, assuming the task is to simply feed the stream of send/receive actions through the relevant FSMs (and detect violations).

**Comment by objectiser** [comment]
The initial sentence was referring to a FSM per role.

I guess we need to define the terms so it is clear to everyone. For example - if we use 'session instance' then does a single instance refer to the global protocol, or is there a session instance per local protocol - and therefore a global 'session' is composed of a set of local 'session instances'.

**Comment by rhu1** [comment]
In your original post, does "session instance" mean global or local?

So input is a "set of FSMs" and a "trace".  "Set of FSMs" means, given a source protocol, the set containing the FSM for each of role in the protocol.  Need to clarify "trace" -- is it a totally ordered series of every action performed by each role?

**Comment by objectiser** [comment]
I think for clarity it might be best to use the terms "LocalSessionInstance" and "GlobalSessionInstance" - although not sure whether the global instance would be required (will have to see) as it is just a collection of the local instances associated with the 'business transaction instance' (for want of a better term).

Although I have mentioned 'trace' - it is probably better if we generalise it to be an "event stream" - where the events may be associated with multiple roles and session instances being monitored concurrently. However the assumption should be totally ordered for a specific role and session instance. Does that sound reasonable?

**Comment by rhu1** [comment]
Closing due to age.  Can reopen if needed in future.
