### ISSUE TITLE
Move scribble artifacts out of modules folder

### ISSUE THREAD

**Issue by objectiser** [scribble/scribble-java#109]
As raised by @rhu1 via email, it would be better for the artifact folder names to reflect the artifact id - and as the modules folder no longer has its own pom (as the artifacts are in the main org.scribble groupId), it would be better to locate them under the top level folder.

Therefore,the sub-folders in the existing `modules` folder should be moved up a level (removing the `modules` folder), and renamed to include prefix `scribble-`. The root pom.xml should then be update to reference the new location/names.

**Comment by objectiser** [comment]
@rhu1 As you may be in the middle of working on the monitor prototype thought I would not do this change now - so either you could do it or assign back to me after the monitoring prototype merged.

**Comment by rhu1** [comment]
@objectiser I can do this -- now is a good point, so I will do shortly.
