### ISSUE TITLE
Is there updated documentation on this?  attempting to use Scribble protocols

### ISSUE THREAD

**Issue by feetheprodigy** [scribble/scribble-java#134]
The wiki documentation does not seem to line up with the code.

https://github.com/scribble/scribble-java/wiki/SJDGProtocol references classes like org.scribble.parser.ProtocolParser pp=new org.scribble.parser.ProtocolParser(); which seem to no longer exist since v0.4.x 

should we not be using this version 4?  is there any documentation for v4 that describes how to parse scribble syntax as it seems to have been rewritten or at least heavily refactored from the from the current developer guides

**Comment by Chalolennox** [comment]
@feetheprodigy  here is the new tutorial
http://www.scribble.org/docs/scribble-java.html#QUICK

I have managed to compile the  demos with eclipse and compiled the Adder example, though I have a feeling AdderC isn't connecting.  The server is listening.  Any suggestions?

**Comment by Chalolennox** [comment]
I take it back, everything worked fine. I am a big fun of your amazing work.

**Comment by rhu1** [comment]
Closing -- thanks for that feedback, it looks like the issue was resolved at the time.
Feel free to reopen or get in touch if this is still an issue.
