### ISSUE TITLE
running scribblec.sh from command line only opens a window which then closes immediately

### ISSUE THREAD

**Issue by JelleBouma** [scribble/scribble-java#149]
I am trying to follow the tutorial at http://www.scribble.org/docs/scribble-java.html
I used eclipse to "Maven install" the project and extracted the resulting zip file.
On Windows, both `scribblec.sh --help` and `scribblec.sh scribble-demos/scrib/tutorial/src/tutorial/adder/Adder.scr -api Adder C -d scribble-demos/scrib/tutorial/src/` have the same result: a black window with a caret opens and immediately closes. No endpoints were generated for the adder.
The window has the following title: "usr/bin/bash --login -i" followed by the path of scribblec.sh and the parameters (e.g. --help).

**Comment by rhu1** [comment]
scribblec.sh is a shell script.  How are you trying to run it?  On Windows you could use WSL or Cygwin, for example.

**Comment by JelleBouma** [comment]
Thanks, running it with Cygwin I get the following error however:
![cygwin](https://user-images.githubusercontent.com/24208642/107813573-e2934880-6d70-11eb-8843-2714d5136308.png)

**Comment by rhu1** [comment]
From what I can tell, your current problem does not specifically relate to Scribble -- looks more like a general issue with running shell scripts in your environment.  Feel free to report any errors from Scribble itself, but I don't think I can directly help with your current problem.

**Comment by rhu1** [comment]
I found an old Cygwin setup, and a quick test seems fine.

![cygwin](https://user-images.githubusercontent.com/3187428/107954359-421d6e00-6f94-11eb-974b-4f1f864c7cde.png)

**Comment by JelleBouma** [comment]
Scribble does run for me on Ubuntu on a virtual machine but that is far from ideal.
Would it be possible to get it to run without the shell script? For example by running it with an IDE?

**Comment by rhu1** [comment]
Sure -- it's just a Java program.  If you run the script with a `--verbose` flag, it should echo the exact java incantation being run.  Or you could just look it up within the script.  Basically, [org.scribble.cli.CommandLine](https://github.com/scribble/scribble-java/blob/master/scribble-cli/src/main/java/org/scribble/cli/CommandLine.java) is the frontend class, and the scribblec script just feeds it the CL arguments.

**Comment by JelleBouma** [comment]
Thanks I got it running, cloning the github repository with IntelliJ.
I did run into a problem where IntelliJ could not find package `org.scribble.parser.antlr` but I solved it by running `antlr-3.5.2-complete.jar` with program arguments `-o scribble-parser/target/generated-sources/antlr3 scribble-parser/src/main/antlr3/org/scribble/parser/antlr/Scribble.g` and then marking the directory `scribble-parser/target/generated-sources/antlr3` as `Sources Root` so the generated java files were detected.
