### ISSUE TITLE
Support module level projection

### ISSUE THREAD

**Issue by objectiser** [scribble/scribble-java#74]
Currently the core requires the module file, protocol and role to be specified, which results in a local protocol being generated in a module named "<module>_<protocol>_<role>".

Although this may be useful in situations where only the individual protocol is required - other situations (such as in tooling environments that operate on the module level), would be easier if the project could be done based on the module and role - resulting in a module named "<module>_<role>" and containing a project of all the protocols in the global module.

**Comment by objectiser** [comment]
One of the issues with the current scribble approach is that there is no naming conventions between global and local protocols - so in one case a global and local protocol could both exist within the same module, in another case, a global protocol and associated projected local protocol could be in separate modules, where the module name of the local protocol is composed of the global module's name and protocol/role names - or in yet another case, the global protocol and local modules could be in completely independent module names.

The issue is, if there is no correlation between the names of global and locally projected protocols, then it is not possible for tooling to implicitly generate one protocol from the other (i.e. projection or deriving global from local) - and more specifically if someone changes either global or local, it is not easy to locate the other protocol and perform validation to identify any conflicts - without further details to help locate the related protocol definitions.

So from a tooling perspective, I think it would be good to define a convention that can be supported by the projection approach.

**Comment by objectiser** [comment]
@rhu1 are you ok with supporting a module level projection? It can be in addition to the protocol level approach currently used. If ok with it, will you be able to implement?

**Comment by rhu1** [comment]
Closing due to age.  Can reopen if needed in future.
